version: "3.7"
services:
  backend:
    build: .
    image: venyunoc/weather-monitoring:latest
    container_name: weather_backend
    networks:
      - backend
    volumes:
      - ./app:/usr/src/app
  influx:
    image: influxdb:1.7-alpine
    container_name: influx
    networks:
      - backend
      - monitoring
networks:
  monitoring:
    external: true
  backend:
