version: "3.7"
services:
  backend:
    build: .
    image: venyunoc/weather-monitoring:latest
    container_name: weather_backend
    networks:
      - monitoring
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - influx
      - proxy
  influx:
    image: influxdb:1.7-alpine
    container_name: influx
    networks:
      - monitoring
    volumes:
      - "/opt/data/influx:/var/lib/influxdb"
    ports:
      - "8086:8086"
  proxy:
    image: venyunoc/radar-proxy:latest
    container_name: proxy
    networks:
      - monitoring
    ports:
      - "5000:5000"
networks:
  monitoring:
    external: true
